### ISSUE TITLE
info.json error

### ISSUE THREAD

**Issue by IzzySoft** [Benojir/Android-Call-Recorder#1]
your [info.json](https://raw.githubusercontent.com/Benojir/Android-Call-Recorder/main/magisk/updates/release/info.json) for automated updates has a little issue:

```json
"zipUrl": "https://github.com/Benojir/Android-Call-Recorder/releases/download/1.4/Call-Recorder_v1.5-Magisk.zip",
```

points to the v1.5 zip at the v1.4 tag, but of course it doesn't exist there. Guess you forgot to update the path with the last release :wink:

**Comment by Benojir** [comment]
Oops! That was my mistake. Thank you for reporting.

**Comment by IzzySoft** [comment]
Thanks for fixing! You can find your module in the [IzzyOnDroid Magisk Repo](https://apt.izzysoft.de/magisk) now (which can be accessed e.g. with the [MMRL](https://apt.izzysoft.de/packages/com.dergoogler.mmrl/) app as "Magisk Manager") :smiley:
