### ISSUE TITLE
[FEATURE REQUEST] Improve recording quality 

### ISSUE THREAD

**Issue by HarriBuh** [Benojir/Android-Call-Recorder#2]
...if possible. The quality of the records is so horrible, I can hardly understand anything of it. If there was a possibility of improving/ increasing the bitrate (or even adding several quality options so that one can choose between size and quality?), it would make this app finally useful to me.
If not, I won't use it any longer.

Cheers.

**Comment by Benojir** [comment]
Thank you for your feedback. I will increase the audio quality and also add options for changing the recording settings in the future update soon

**Comment by HarriBuh** [comment]
So.. How is the update going? Any news about it?

**Comment by Benojir** [comment]
Join here and chat us https://t.me/CreativePapaGroup

**Comment by HarriBuh** [comment]
Not using Telegram, sorry. I guess I'll just wait then.

**Comment by HarriBuh** [comment]
It's 2 months and no update. Thanks for nothing. Closing as not planned.
